<a href="https://colab.research.google.com/github/KKOKKOMO/Butcamp-ML/blob/main/less_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([[-1, 2, 4], [2, 0, -1]])
b = np.array([[5, 2, 3], [4, 6, 2]])

In [ ]:
a, type(a)

(array([[-1,  2,  4],
        [ 2,  0, -1]]), numpy.ndarray)

In [ ]:
b, type(b)

(array([[2, 1],
        [1, 2]]), numpy.ndarray)

In [ ]:
a + b

array([[4, 4, 7],
       [6, 6, 1]])

In [ ]:
a - b

array([[-6,  0,  1],
       [-2, -6, -3]])

In [ ]:
a = np.array([[1, 2], [2, -1], [3, 0]])
b = np.array([[-1, 1], [1, 2], [0, 0]])

In [ ]:
c =  a - b*3

In [ ]:
c

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

In [ ]:
a = np.array([[1, -1], [2, 0], [3, 0]])
b = np.array([[1, 1], [2, 0]])
c = a@b
c

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

In [ ]:
a = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(a)

-95.99999999999999

In [ ]:
a = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])
a_inv = np.linalg.inv(a)
a_inv_inv = np.linalg.inv(a_inv)
if a_inv_inv.all() == a.all():
  print(f'TRUE\n {a_inv}\n{a_inv_inv}\n{a}')

TRUE
 [[ 0.07407407  0.14814815  0.18518519]
 [ 0.2037037  -0.09259259 -0.24074074]
 [-0.16666667  0.16666667 -0.16666667]]
[[ 3.  3. -1.]
 [ 4.  1.  3.]
 [ 1. -2. -2.]]
[[ 3  3 -1]
 [ 4  1  3]
 [ 1 -2 -2]]
